/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './public/index.html',
    './tailwind.config.js/',
    './tailwind-default.config.js',
    './public/all-events.html',
    './public/vision-trip.html',
  ],
  theme: {
    extend: {
      height: {
        icon: '5rem',
        sm: '1.31rem',
        c: '1.30rem',
        c2: '3rem',
        c3: '3.75rem',
      },
      width: {
        icon: '5rem',
        sm: '1.31rem',
      },
      spacing: {
        footer: '3rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '12': '3rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        nav: '20rem',
        navsm: '20rem',
        navmd: '15rem',
      },
      margin: {
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '12': '3rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        nav: '20rem',
        navsm: '3rem',
        navmd: '15rem',
      },
      padding: {
        "fluid-video": "56.25%",
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '12': '3rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
      },
      colors: {
        primary: '#00bae0',
        hover: '#3993B0',
        dark: '#2f2f2f',
        builders: '#003E50',
        sage: '#B5C6B5',
        cream: '#F7F0EA',
        yam: '#CC4E2B',
        footer: '#6c6c6c',
      },
      fontFamily: {
        sans: ['Barlow', 'sans-serif'],
        heading:['Barlow', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
